//! Real Git generated bytes, owner-fenced SQL rollback and exact SDK recovery.
use super::*;
use super::{
    native_candidate::{candidate, catalog, initial, ready, write},
    native_merge,
    prepare::{cleaned, opened},
    publishing::edit,
};
use crate::{
    git_gateway::candidates::ProducedCandidate,
    packs::verification::physical::tests::prepared_for_store,
    pulls::{
        candidates::{CandidateResult, MergeCandidate, commit_body},
        merge::MergeStrategy,
    },
};
use canopy_object_storage::artifact::{ArtifactKey, ArtifactKind};
use cellule_runtime::{PreparedCommand, Resolution};
use object_store::ObjectStoreExt;

async fn reserve(f: &Fixture, candidate: &MergeCandidate) -> Result {
    let candidate = candidate.clone();
    f.handle.execute(identity()?,Digest::from_bytes([218;32]),sql::now(0)?,4096,0,move|tx| {
        let id=uuid::Uuid::parse_str(&candidate.request.id).map_err(|_|Error::Command("candidate fixture UUID"))?;
        let binding=crate::pulls::candidates::intent_binding(&candidate)?;
        let request=serde_json::to_string(&candidate.request).map_err(|_|Error::Command("candidate fixture request"))?;
        let result=serde_json::to_string(&CandidateResult::Pending).map_err(|_|Error::Command("candidate fixture result"))?;
        tx.execute("INSERT INTO merge_candidates(id,binding,pull_number,actor,request,created_ms,result,source_oid,base_oid) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9)",rusqlite::params![id.as_bytes().as_slice(),binding,candidate.number,candidate.actor,request,candidate.created_at_ms,result,crate::pulls::merge::oid(&candidate.request.revision.source_oid)?.as_ref(),crate::pulls::merge::oid(&candidate.request.revision.base_oid)?.as_ref()])?;
        Ok(cellule_runtime::cell::executor::HandlerOutcome::Success(vec![]))
    }).await?;
    Ok(())
}
async fn state(f: &Fixture) -> Result<Vec<u8>> {
    let roots = super::publishing::state(&f.handle).await?;
    let editorial=f.handle.query(0,65536,|db| {
        let candidate:(String,Option<Vec<u8>>,Option<Vec<u8>>)=db.query_row("SELECT result,oid,native_publication FROM merge_candidates",[],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?)))?;
        let mut query=db.prepare("SELECT recovery_phase,recovery_phase_revision FROM catalog_leases ORDER BY admission_sequence")?;
        let phases=query.query_map([],|r|Ok((r.get::<_,Option<Vec<u8>>>(0)?,r.get::<_,u64>(1)?)))?.collect::<rusqlite::Result<Vec<_>>>()?;
        serde_json::to_vec(&(candidate,phases)).map_err(|_|Error::Command("candidate fixture state"))
    }).await?;
    Ok([roots, editorial].concat())
}
async fn command(
    f: &Fixture,
    prepared: &PreparedCatalog,
    candidate: MergeCandidate,
    root: &std::path::Path,
    budget: cellule_ltx::DiskBudget,
) -> Result<(
    PreparedCommand<PublishNativeCandidate>,
    RegisteredRootRecovery,
)> {
    let produced = ProducedCandidate::verified_fixture(candidate, prepared.token().operation);
    let proof = prepared
        .native_candidate_proof(
            &produced,
            root,
            budget,
            crate::packs::metadata::tests::limits(),
        )
        .await?;
    let command = f
        .client()
        .prepare_command::<PublishNativeCandidate>(&f.target, identity()?, proof)
        .await?;
    let registered = super::super::recovery::persist(
        &prepared.base.session,
        &command,
        super::super::recovery::Kind::Candidate,
        &prepared.base.indexes().store(),
        identity()?,
        0,
    )
    .await?;
    Ok((command, registered))
}
#[tokio::test]
async fn native_candidate_ready_is_atomic_retained_and_recovers_original_receipt_after_body_retirement()
-> Result {
    for format in [ObjectFormat::Sha1, ObjectFormat::Sha256] {
        let (f, graph, merge) = native_merge::initial(format, false).await?;
        let (base, _, _) =
            opened(&f, *uuid::Uuid::new_v4().as_bytes(), graph.store.clone()).await?;
        let mut native = prepared_for_store(
            format,
            4,
            base.context().operation,
            graph.provider.clone(),
            graph.store.clone(),
        )
        .await?;
        // Install the real accepted base pack into this isolated fixture so
        // stock Git can traverse the generated commit's original parents.
        let reader =
            crate::packs::catalog::CatalogReader::open(base.indexes(), graph.prepared.catalog())
                .await?;
        let files = base.files();
        let pack = reader
            .lookup(graph.tip, &*files, &*files)
            .await?
            .ok_or("base source")?
            .source
            .record
            .native();
        let mut body = graph
            .store
            .read(pack.key(ArtifactKind::Pack)?, pack.pack)
            .await?;
        let mut bytes = Vec::new();
        while let Some(chunk) = body.next().await? {
            bytes.extend_from_slice(&chunk);
        }
        crate::packs::verification::physical::tests::independence::git_input(
            native.fixture.root.path(),
            &["index-pack", "--stdin"],
            &bytes,
        )
        .await?;
        let (first, tree) = initial(&native)?;
        assert_eq!(first, graph.initial);
        let mut pending = candidate(MergeStrategy::MergeCommit, graph.initial, graph.tip);
        pending.request.revision = merge.revision;
        reserve(&f, &pending).await?;
        let generated = write(
            &native,
            &commit_body(&pending, &hex::encode(tree)),
            "refs/heads/generated",
        )
        .await?;
        let completed = ready(&pending, generated, tree);
        let (prepared, root, budget) = catalog(&f, &mut native, base).await?;
        let check = prepared.base.capability().2.clone();
        let (command, saved) =
            command(&f, &prepared, completed, root.path(), budget.clone()).await?;
        edit(&f,"CREATE TRIGGER abort_candidate BEFORE UPDATE OF result ON merge_candidates BEGIN SELECT RAISE(ABORT,'late candidate failure'); END;").await?;
        let before = state(&f).await?;
        assert!(command.clone().execute().await.is_err());
        assert_eq!(state(&f).await?, before);
        assert!(matches!(
            f.client().resolve(command.evidence()).await?,
            Resolution::Absent
        ));
        edit(&f, "DROP TRIGGER abort_candidate").await?;
        let original = command.clone().execute().await?;
        assert!(matches!(
            original.output,
            CandidatePublicationReply::Applied {
                publication: Some(PublishedRefs {
                    generation: 2,
                    ref_generation: 2,
                    ..
                }),
                ..
            }
        ));
        assert_eq!(command.execute().await?.receipt, original.receipt);
        let selected = f
            .handle
            .query(0, 1024, |db| {
                assert_eq!(
                    db.query_row("SELECT generation FROM ref_generation", [], |r| r
                        .get::<_, i64>(0))?,
                    2
                );
                assert_eq!(
                    db.query_row("SELECT count(*) FROM refs", [], |r| r.get::<_, i64>(0))?,
                    0
                );
                assert!(
                    db.execute("UPDATE merge_candidates SET created_ms=created_ms+1", [])
                        .is_err()
                );
                assert!(
                    db.execute("UPDATE merge_candidates SET result='{}'", [])
                        .is_err()
                );
                assert!(db.execute("DELETE FROM merge_candidates", []).is_err());
                db.query_row("SELECT native_publication FROM merge_candidates", [], |r| {
                    r.get::<_, Vec<u8>>(0)
                })
                .map_err(Into::into)
            })
            .await?;
        let mut decoder = BoundedDecoder::new(&selected, 512)?;
        let selected = super::super::candidate_publication::audit::Selected::decode(&mut decoder)?;
        decoder.finish()?;
        let audit = selected.root.ok_or("candidate audit absent")?;
        let path = graph.store.path(
            ArtifactKey {
                operation: audit.operation,
                binding_digest: audit.artifact.digest,
                kind: ArtifactKind::InputRoot,
            },
            audit.artifact.digest,
        )?;
        let bytes = graph.provider.get(&path).await?.bytes().await?;
        graph.provider.delete(&path).await?;
        let admin = super::terminal_retention::maintenance(&f.handle, f.repository).await?;
        assert!(
            saved
                .ready_terminal_release(f.client(), &graph.store, admin.clone(), identity()?)
                .await
                .is_err()
        );
        graph.provider.put(&path, bytes.into()).await?;
        assert_eq!(
            saved
                .ready_terminal_release(f.client(), &graph.store, admin, identity()?)
                .await?
                .complete()
                .await?
                .output,
            TerminalReleaseReply::Released
        );
        for (key, descriptor) in saved.command_bodies_for_test() {
            graph
                .provider
                .delete(&graph.store.path(key, descriptor.digest)?)
                .await?;
        }
        drop(prepared);
        cleaned(root.path(), &budget).await?;
        let (runtime, handle, client) = super::durable_recovery::restore_owner(&f, &check).await?;
        assert!(handle.owner_fence().epoch > check.token.owner.epoch);
        let restored = RegisteredRootRecovery::load(&client, &f.target, &graph.store, &check)
            .await?
            .ok_or("candidate recovery archive absent")?;
        let PublicationOutcome::Candidate(replay) = restored
            .dispatch_any(
                &client,
                &graph.store,
                &f.authority(),
                &std::sync::atomic::AtomicBool::new(false),
            )
            .await?
        else {
            return Err("wrong candidate recovery purpose".into());
        };
        assert_eq!(
            (replay.output, replay.receipt),
            (original.output, original.receipt)
        );
        runtime.shutdown().await?;
        drop(graph.prepared);
        cleaned(graph.root.path(), &graph.budget).await?;
    }
    Ok(())
}

#[tokio::test]
async fn large_negative_candidate_uses_compact_ack_without_publishing_roots() -> Result {
    use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
    for format in [ObjectFormat::Sha1, ObjectFormat::Sha256] {
        let (f, graph, merge) = native_merge::initial(format, false).await?;
        let (prepared, root, budget) = native_merge::preparation(&f, &graph).await?;
        let mut pending = candidate(MergeStrategy::MergeCommit, graph.initial, graph.tip);
        pending.request.revision = merge.revision;
        reserve(&f, &pending).await?;
        let mut completed = pending;
        completed.result = CandidateResult::Conflicted {
            paths_base64: vec![URL_SAFE_NO_PAD.encode(vec![b'x'; 256]); 700],
        };
        assert!(crate::pulls::candidates::valid_result(&completed.result));
        assert!(serde_json::to_vec(&completed.result)?.len() > 200 << 10);
        let (command, saved) =
            command(&f, &prepared, completed, root.path(), budget.clone()).await?;
        let before = f
            .handle
            .query(0, 1024, |db| {
                Ok(db
                    .query_row("SELECT generation FROM catalog_state", [], |r| {
                        r.get::<_, u64>(0)
                    })?
                    .to_le_bytes()
                    .to_vec())
            })
            .await?;
        let original = command.execute().await?;
        assert!(matches!(
            original.output,
            CandidatePublicationReply::Applied {
                publication: None,
                ..
            }
        ));
        let mut encoded = BoundedEncoder::new(512)?;
        original.output.encode(&mut encoded)?;
        assert!(encoded.finish().len() < 128);
        assert_eq!(
            f.handle
                .query(0, 1024, |db| Ok(db
                    .query_row("SELECT generation FROM catalog_state", [], |r| r
                        .get::<_, u64>(0))?
                    .to_le_bytes()
                    .to_vec()))
                .await?,
            before
        );
        let admin = super::terminal_retention::maintenance(&f.handle, f.repository).await?;
        assert_eq!(
            saved
                .ready_terminal_release(f.client(), &graph.store, admin, identity()?)
                .await?
                .complete()
                .await?
                .output,
            TerminalReleaseReply::Released
        );
        drop(prepared);
        cleaned(root.path(), &budget).await?;
        drop(graph.prepared);
        cleaned(graph.root.path(), &graph.budget).await?;
        f.runtime.shutdown().await?;
    }
    Ok(())
}
